### ISSUE TITLE
See info for cars other than player?

### ISSUE THREAD

**Issue by jessemillar** [SVappsLAB/iRacingTelemetrySDK#11]
I'm newer to iRacing telemetry, but when I work with SimHub's view into the raw iRacing telemetry data, there's various values prefaced with "CarIdx" which allows me to see certain stats about cars other than mine on the track. I see those properties listed in your `iRacingData.cs` file but when I run your sample program that outputs all variables to a .csv file against an .ibt from a recent session, I don't see any CarIdx values. Are these values not exposed? Or am I just doing something wrong? I tried accessing the values in various ways and get build errors like the following:

```
fail: logger[0] error playing ibt file System.Exception: the telemetry value 'CarIdxLap' does not exist    at SVappsLAB.iRacingTelemetrySDK.irSDKMemoryAccessProvider.GetVarValue(String varName)    at SVappsLAB.iRacingTelemetrySDK.TelemetryClient`1.<GetTelemetryDataSample>b__41_0(ParameterInfo p)    at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()    at SVappsLAB.iRacingTelemetrySDK.TelemetryClient`1.GetTelemetryDataSample()    at SVappsLAB.iRacingTelemetrySDK.TelemetryClient`1.ProcessIbtData(CancellationToken token)
```

**Comment by jessemillar** [comment]
Ah. I was too hasty. Looks like `CarIdxLapDistPct` is available but only when viewing live telemetry, not when looking at an .ibt file. I'd guess an .ibt file only contains player data.

**Comment by SVappsLAB** [comment]
right.  the `iRacingData.cs` file is used internally to facilitate code generation for generating the variable types.  it's a list of all known variables.

however, the variables available from live and ibt files is different.  in fact, even the 'live' variables can be different between cars. 

to see what variables are available (live or ibt files) ,  you can use the `DumpVariables_DumpSessionInfo`  sample to dump the variables to a csv file
https://github.com/SVappsLAB/iRacingTelemetrySDK/tree/main/Samples
