### ISSUE TITLE
Readme not working

### ISSUE THREAD

**Issue by p3dr0thor** [SVappsLAB/iRacingTelemetrySDK#9]
Hi, i'm using tutorial on readme but i got error saying 

RequiredTelemetryVars and TelemetryData not exists, i tried download and execute sample but i got same error

**Comment by rcmx** [comment]
a few things to check
1. make sure you have .net 8 sdk installed (https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
2. when you open an example project  
(like https://github.com/SVappsLAB/iRacingTelemetrySDK/tree/main/Samples/SpeedRPMGear)
in Visual Studio,  double check that all nuget packages are restored.  this sample should build and run without any changes

**Comment by SVappsLAB** [comment]
a few things to check
1. make sure you have .net 8 sdk installed (https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
2. when you open an example project  
(like https://github.com/SVappsLAB/iRacingTelemetrySDK/tree/main/Samples/SpeedRPMGear)
in Visual Studio,  double check that all nuget packages are restored.  this sample should build and run without any changes

**Comment by SVappsLAB** [comment]
@p3dr0thor any luck with this?
